### ISSUE TITLE
Partial transition function crashes raft node

### ISSUE THREAD

**Issue by gdijkstra** [adjoint-io/raft#90]
If the user-supplied method `applyCmdRSMP :: RSMPCtx sm v -> sm -> v -> Either (RSMPError sm v) sm` returns a `Left`, the event loop (`handleEventLoop`) halts as `applyLogEntries` panics.

However, getting a `Left` from the user-supplied `applyCmdRSMP` might be a recoverable error, e.g. we could not update the state of the state machine and record the invalid command somewhere.

To deal with this, we could have an interface for a raft node allowing us to query the status of a client write request: a command might be pending, applied or rejected (if `applycmdRSMP` returned a `Left`).

**Comment by tdietert** [comment]
This will be necessary for integration into `uplink` as invalid transactions can indeed be submitted to the system inadvertently such that the "transaction status" (log entry status) should be queryable. It should be easy enough to extend the client response interface to handle this case.

It is worth discussing if we should store all invalid log entries submitted, too, though at the moment I cannot think of a reason why other than "because we did it before".

**Comment by tdietert** [comment]
I will be testing this later today inside of `uplink` and expect to see crashes on invalid transactions submitted. This feature may be implemented soon, as a result.

**Comment by tdietert** [comment]
Closing, resolved by #136.
